# Generated by Django 3.0.5 on 2020-04-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='account',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(default='user.png', storage='user_image/', upload_to=''),
        ),
        migrations.AddField(
            model_name='account',
            name='skills',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='account',
            name='work_line',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
